const Constants = {
  RECEIVE_PROFILE: 'RECEIVE_PROFILE',
  REMOVE_PROFILE: 'REMOVE_PROFILE',
  // RECEIVE_PROFILES: 'RECEIVE_PROFILES',
  RECEIVE_PROJECT: 'RECEIVE_PROJECT'
};

export default Constants;
